server:
  port: 10010

spring:
  application:
    name: live-gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/

zuul:
  prefix: /api

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #服务熔断超时时间5s

ribbon:
  ConnectTimeout: 1000 #ribbon连接超时时间
  ReadTimeout: 3500 #ribbon读取超时
  MaxAutoRetries: 0 #重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数